version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs:rw
      - ssl_certs:/etc/letsencrypt:ro
    environment:
      - GO_ENV=production
      - JWT_SECRET=change_this_in_production
    networks:
      - secretbay-network
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:rw
      - ssl_certs:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    networks:
      - secretbay-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ssl_certs:/etc/letsencrypt:rw
      - certbot_www:/var/www/certbot:rw
    entrypoint: sh -c 'sleep 10 && certbot certonly --webroot --webroot-path=/var/www/certbot --email admin@example.com --agree-tos --no-eff-email -d localhost --staging --non-interactive || true'

networks:
  secretbay-network:
    driver: bridge

volumes:
  ssl_certs:
    driver: local
  certbot_www:
    driver: local