version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - ssl_certs:/etc/letsencrypt
    environment:
      - GO_ENV=production
      - JWT_SECRET=change_this_in_production
    networks:
      - secretbay-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ssl_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - secretbay-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  certbot:
    image: certbot/certbot
    volumes:
      - ssl_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@example.com --agree-tos --no-eff-email -d localhost --staging
    depends_on:
      - frontend

networks:
  secretbay-network:
    driver: bridge

volumes:
  logs:
  ssl_certs:
  certbot_www: