name: secretbay_lite
description: Cross-platform VPN configuration tool
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  file_picker: ^5.3.2
  ssh: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
